---
title: "Research Methods II"
subtitle: "Micro-path"
author: Fernando Rios-Avila
format: 
  html:
    code-fold: true
    echo: true
    css: styles.css 
---

## Syllabus

If you are reading this, you are probably enrolled in the course. This page will contain information about the course, including the syllabus, assignments, and other relevant information.

As the course progresses, I will add links to the syllabus, assignments, and other relevant information.

## Sessions

**Session 1: Surveys, IO and SAM** 

Slides: [html](session_1.qmd) and [pdf](session_1.pdf)

Readings: [link]

**Session 2: MLE & Limited Dependent Variables** 

Slides: [html](session_2.qmd) and [pdf](session_2.pdf)

Readings: [link]

**Session 3: Measuring Inequality** 

Slides: [html](session_3.qmd) and [pdf](session_3.pdf)

Readings: [link]

**Session 4: Analyzing Gaps** 

Slides: [html](session_4.qmd) and [pdf](session_4.pdf)

Readings: [link]

**Session 5: Significance and Missing Data** 

Slides: [html](session_5.qmd) and [pdf](session_5.pdf)

Readings: [link]

**Session 6: Imputation: Statistical Matching** 

Slides: [html](session_6.qmd) and [pdf](session_6.pdf)
Readings: [link]

**Session 7: Session 7: Micro-Simulations, and Monte Carlo Methods** 

Slides: [html](session_7.qmd) and [pdf](session_7.pdf)
Readings: [link]